In [2]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("Vectorized version:" + str(1000*(toc-tic)) + "ms")

c = 0

tic = time.time()

for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For loop:" + str(1000*(toc-tic)) + "ms")

Vectorized version:2.998828887939453ms
249825.72776287934
For loop:836.7290496826172ms


In [10]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])

In [12]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [13]:
100*A/cal.reshape(1,4)

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

### Python-Numpy Vectors

In [20]:
a = np.random.randn(5)
a

array([ 1.17981487, -1.46514042, -0.02930865,  0.89420834, -0.72145972])

In [21]:
a.shape

(5,)

In [22]:
a = np.random.randn(5,1)
a

array([[-1.18444138],
       [ 2.8704555 ],
       [-0.9641198 ],
       [-0.1461007 ],
       [-1.34934201]])

In [27]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
c

array([[ 0.20685981, -1.11957595, -0.06607047],
       [-0.66966098, -3.33578026,  0.69249981]])

In [28]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [30]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
c.shape

(12288, 45)

In [32]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c

array([[ 0.06835855, -0.26816637, -0.56370511],
       [-0.03837284, -0.08276337,  0.25427881],
       [ 0.08438993,  0.90827422, -0.30130331]])